controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

share_linkedin:
    path: '/share/linkedin'
    controller: App\Controller\ShareController::shareOnLinkedIn
